// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

/*
Package serialisation is a generated protocol buffer package.

It is generated from these files:
	file.proto

It has these top-level messages:
	FileDescriptorProto
	FileProto
	FileDescriptorProtoList
	OpenTxRequest
	OpenTxResponse
*/
package serialisation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileDescriptorProto struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Hash     string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
}

func (m *FileDescriptorProto) Reset()                    { *m = FileDescriptorProto{} }
func (m *FileDescriptorProto) String() string            { return proto.CompactTextString(m) }
func (*FileDescriptorProto) ProtoMessage()               {}
func (*FileDescriptorProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FileDescriptorProto) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileDescriptorProto) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type FileProto struct {
	Descriptor_ *FileDescriptorProto `protobuf:"bytes,1,opt,name=descriptor" json:"descriptor,omitempty"`
	Contents    []byte               `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (m *FileProto) Reset()                    { *m = FileProto{} }
func (m *FileProto) String() string            { return proto.CompactTextString(m) }
func (*FileProto) ProtoMessage()               {}
func (*FileProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FileProto) GetDescriptor_() *FileDescriptorProto {
	if m != nil {
		return m.Descriptor_
	}
	return nil
}

func (m *FileProto) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type FileDescriptorProtoList struct {
	FileDescriptorList []*FileDescriptorProto `protobuf:"bytes,1,rep,name=fileDescriptorList" json:"fileDescriptorList,omitempty"`
}

func (m *FileDescriptorProtoList) Reset()                    { *m = FileDescriptorProtoList{} }
func (m *FileDescriptorProtoList) String() string            { return proto.CompactTextString(m) }
func (*FileDescriptorProtoList) ProtoMessage()               {}
func (*FileDescriptorProtoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FileDescriptorProtoList) GetFileDescriptorList() []*FileDescriptorProto {
	if m != nil {
		return m.FileDescriptorList
	}
	return nil
}

type OpenTxRequest struct {
	FileDescriptorList *FileDescriptorProtoList `protobuf:"bytes,1,opt,name=fileDescriptorList" json:"fileDescriptorList,omitempty"`
}

func (m *OpenTxRequest) Reset()                    { *m = OpenTxRequest{} }
func (m *OpenTxRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenTxRequest) ProtoMessage()               {}
func (*OpenTxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OpenTxRequest) GetFileDescriptorList() *FileDescriptorProtoList {
	if m != nil {
		return m.FileDescriptorList
	}
	return nil
}

type OpenTxResponse struct {
	RevisionStr        string                   `protobuf:"bytes,1,opt,name=revisionStr" json:"revisionStr,omitempty"`
	FileDescriptorList *FileDescriptorProtoList `protobuf:"bytes,2,opt,name=FileDescriptorList" json:"FileDescriptorList,omitempty"`
}

func (m *OpenTxResponse) Reset()                    { *m = OpenTxResponse{} }
func (m *OpenTxResponse) String() string            { return proto.CompactTextString(m) }
func (*OpenTxResponse) ProtoMessage()               {}
func (*OpenTxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OpenTxResponse) GetRevisionStr() string {
	if m != nil {
		return m.RevisionStr
	}
	return ""
}

func (m *OpenTxResponse) GetFileDescriptorList() *FileDescriptorProtoList {
	if m != nil {
		return m.FileDescriptorList
	}
	return nil
}

func init() {
	proto.RegisterType((*FileDescriptorProto)(nil), "serialisation.FileDescriptorProto")
	proto.RegisterType((*FileProto)(nil), "serialisation.FileProto")
	proto.RegisterType((*FileDescriptorProtoList)(nil), "serialisation.FileDescriptorProtoList")
	proto.RegisterType((*OpenTxRequest)(nil), "serialisation.OpenTxRequest")
	proto.RegisterType((*OpenTxResponse)(nil), "serialisation.OpenTxResponse")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xd9, 0x2a, 0x62, 0xa7, 0xd6, 0x43, 0x3c, 0xb8, 0x78, 0x5a, 0x72, 0x10, 0x4f, 0x7b,
	0xd0, 0x37, 0x10, 0xed, 0x49, 0x50, 0xa2, 0x78, 0x8f, 0x75, 0x6a, 0x07, 0xb7, 0x49, 0xcc, 0x8c,
	0xe2, 0x33, 0xf8, 0xd4, 0x92, 0xa8, 0x4b, 0x4b, 0x23, 0xda, 0xdb, 0xce, 0xec, 0x7c, 0xf3, 0xfd,
	0x21, 0x01, 0x98, 0x51, 0x87, 0x6d, 0x88, 0x5e, 0xbc, 0x1a, 0x33, 0x46, 0xb2, 0x1d, 0xb1, 0x15,
	0xf2, 0x4e, 0x5f, 0xc2, 0xc1, 0x84, 0x3a, 0xbc, 0x40, 0x9e, 0x46, 0x0a, 0xe2, 0xe3, 0x4d, 0x9e,
	0x3a, 0x82, 0xdd, 0xc4, 0x38, 0xbb, 0xc0, 0xba, 0x6a, 0xaa, 0x93, 0xa1, 0xe9, 0x6b, 0xa5, 0x60,
	0x7b, 0x6e, 0x79, 0x5e, 0x0f, 0x72, 0x3f, 0x7f, 0xeb, 0x67, 0x18, 0xa6, 0x35, 0x5f, 0xf0, 0x39,
	0xc0, 0x63, 0xbf, 0x2f, 0xe3, 0xa3, 0x53, 0xdd, 0xae, 0x78, 0xdb, 0x82, 0xd4, 0x2c, 0x51, 0x29,
	0xc0, 0xd4, 0x3b, 0x41, 0x27, 0x9c, 0x45, 0x7b, 0xa6, 0xaf, 0xf5, 0x02, 0x0e, 0x0b, 0xf8, 0x15,
	0xb1, 0x28, 0x03, 0x6a, 0xb6, 0xf2, 0x2b, 0x75, 0xeb, 0xaa, 0xd9, 0xfa, 0x67, 0x84, 0x02, 0xad,
	0x9f, 0x60, 0x7c, 0x1d, 0xd0, 0xdd, 0xbd, 0x1b, 0x7c, 0x79, 0x45, 0x16, 0x75, 0xff, 0x8b, 0x24,
	0x9d, 0xf3, 0xf8, 0x6f, 0x49, 0x9a, 0x2e, 0x8a, 0x3e, 0x2a, 0xd8, 0xff, 0x31, 0x71, 0xf0, 0x8e,
	0x51, 0x35, 0x30, 0x8a, 0xf8, 0x46, 0x4c, 0xde, 0xdd, 0x4a, 0xfc, 0xbe, 0x8a, 0xe5, 0x56, 0x0a,
	0x33, 0x59, 0x0f, 0x33, 0xd8, 0x2c, 0xcc, 0xfa, 0x86, 0x87, 0x9d, 0xfc, 0x5c, 0xce, 0x3e, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xa2, 0xca, 0xc0, 0x6e, 0x3c, 0x02, 0x00, 0x00,
}
