// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uploadedfile.proto

/*
Package serialisation is a generated protocol buffer package.

It is generated from these files:
	uploadedfile.proto

It has these top-level messages:
	UploadedFile
*/
package serialisation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UploadedFile struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	File     []byte `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (m *UploadedFile) Reset()                    { *m = UploadedFile{} }
func (m *UploadedFile) String() string            { return proto.CompactTextString(m) }
func (*UploadedFile) ProtoMessage()               {}
func (*UploadedFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UploadedFile) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *UploadedFile) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*UploadedFile)(nil), "serialisation.UploadedFile")
}

func init() { proto.RegisterFile("uploadedfile.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2d, 0xc8, 0xc9,
	0x4f, 0x4c, 0x49, 0x4d, 0x49, 0xcb, 0xcc, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x2d, 0x4e, 0x2d, 0xca, 0x4c, 0xcc, 0xc9, 0x2c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x53, 0xb2, 0xe3,
	0xe2, 0x09, 0x85, 0x2a, 0x72, 0xcb, 0xcc, 0x49, 0x15, 0x92, 0xe2, 0xe2, 0x00, 0x29, 0xce, 0x4b,
	0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x85, 0x84, 0xb8, 0x58, 0x40,
	0x6c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x30, 0x3b, 0x89, 0x0d, 0x6c, 0xaa, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x6b, 0xe9, 0x84, 0xdf, 0x6b, 0x00, 0x00, 0x00,
}
