// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_files/client_upload.proto

/*
Package protobufgenerated is a generated protocol buffer package.

It is generated from these files:
	proto_files/client_upload.proto

It has these top-level messages:
	FileDescriptorProto
	FileProto
	OpenTxRequest
	OpenTxResponse
*/
package protobufgenerated

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileDescriptorProto struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Hash     string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
}

func (m *FileDescriptorProto) Reset()                    { *m = FileDescriptorProto{} }
func (m *FileDescriptorProto) String() string            { return proto.CompactTextString(m) }
func (*FileDescriptorProto) ProtoMessage()               {}
func (*FileDescriptorProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FileDescriptorProto) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileDescriptorProto) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type FileProto struct {
	Hash     string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	Contents []byte `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (m *FileProto) Reset()                    { *m = FileProto{} }
func (m *FileProto) String() string            { return proto.CompactTextString(m) }
func (*FileProto) ProtoMessage()               {}
func (*FileProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FileProto) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *FileProto) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type OpenTxRequest struct {
	FileDescriptors []*FileDescriptorProto `protobuf:"bytes,1,rep,name=fileDescriptors" json:"fileDescriptors,omitempty"`
}

func (m *OpenTxRequest) Reset()                    { *m = OpenTxRequest{} }
func (m *OpenTxRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenTxRequest) ProtoMessage()               {}
func (*OpenTxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OpenTxRequest) GetFileDescriptors() []*FileDescriptorProto {
	if m != nil {
		return m.FileDescriptors
	}
	return nil
}

type OpenTxResponse struct {
	RevisionID int64    `protobuf:"varint,1,opt,name=revisionID" json:"revisionID,omitempty"`
	Hashes     []string `protobuf:"bytes,2,rep,name=hashes" json:"hashes,omitempty"`
}

func (m *OpenTxResponse) Reset()                    { *m = OpenTxResponse{} }
func (m *OpenTxResponse) String() string            { return proto.CompactTextString(m) }
func (*OpenTxResponse) ProtoMessage()               {}
func (*OpenTxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OpenTxResponse) GetRevisionID() int64 {
	if m != nil {
		return m.RevisionID
	}
	return 0
}

func (m *OpenTxResponse) GetHashes() []string {
	if m != nil {
		return m.Hashes
	}
	return nil
}

func init() {
	proto.RegisterType((*FileDescriptorProto)(nil), "protobufgenerated.FileDescriptorProto")
	proto.RegisterType((*FileProto)(nil), "protobufgenerated.FileProto")
	proto.RegisterType((*OpenTxRequest)(nil), "protobufgenerated.OpenTxRequest")
	proto.RegisterType((*OpenTxResponse)(nil), "protobufgenerated.OpenTxResponse")
}

func init() { proto.RegisterFile("proto_files/client_upload.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xcd, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x59, 0x57, 0x8a, 0x3b, 0x7e, 0x61, 0x04, 0x59, 0x3c, 0x68, 0xd9, 0x83, 0xec, 0x69,
	0x05, 0x3d, 0x7a, 0xad, 0xa2, 0x27, 0x4b, 0xf0, 0x5e, 0xd2, 0xed, 0xac, 0x0d, 0xac, 0x93, 0x98,
	0xc9, 0x8a, 0x7f, 0xbe, 0x64, 0xb4, 0xf5, 0xab, 0xa7, 0xe4, 0x4d, 0xde, 0x7b, 0xf9, 0x0d, 0x9c,
	0xfb, 0xe0, 0xa2, 0x9b, 0x75, 0xb6, 0x47, 0xbe, 0x6c, 0x7b, 0x8b, 0x14, 0x67, 0x83, 0xef, 0x9d,
	0x59, 0x34, 0xf2, 0xa2, 0x8e, 0xe4, 0x98, 0x0f, 0xdd, 0x33, 0x12, 0x06, 0x13, 0x71, 0x51, 0xdd,
	0xc2, 0xf1, 0x9d, 0xed, 0x71, 0x82, 0xdc, 0x06, 0xeb, 0xa3, 0x0b, 0x53, 0x71, 0x9e, 0xc2, 0x4e,
	0xaa, 0x21, 0xf3, 0x82, 0x65, 0x36, 0xce, 0xea, 0x42, 0xaf, 0xb5, 0x52, 0xb0, 0xbd, 0x34, 0xbc,
	0x2c, 0xb7, 0x64, 0x2e, 0xf7, 0xea, 0x06, 0x8a, 0x54, 0xf3, 0x19, 0x5e, 0x19, 0xb2, 0x6f, 0x43,
	0x2a, 0x6c, 0x1d, 0x45, 0xa4, 0xc8, 0x12, 0xdc, 0xd3, 0x6b, 0x5d, 0x19, 0xd8, 0x7f, 0xf4, 0x48,
	0x4f, 0xef, 0x1a, 0x5f, 0x07, 0xe4, 0xa8, 0xa6, 0x70, 0xd8, 0xfd, 0x82, 0xe2, 0x32, 0x1b, 0xe7,
	0xf5, 0xee, 0xd5, 0x45, 0xf3, 0x6f, 0x83, 0x66, 0x03, 0xbe, 0xfe, 0x1b, 0xaf, 0xee, 0xe1, 0x60,
	0xf5, 0x05, 0x7b, 0x47, 0x8c, 0xea, 0x0c, 0x20, 0xe0, 0x9b, 0x65, 0xeb, 0xe8, 0x61, 0x22, 0xa8,
	0xb9, 0xfe, 0x31, 0x51, 0x27, 0x30, 0x4a, 0xe0, 0x98, 0x70, 0xf3, 0xba, 0xd0, 0x5f, 0x6a, 0x3e,
	0x12, 0x82, 0xeb, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0x03, 0x71, 0x19, 0x6d, 0x01, 0x00,
	0x00,
}
