// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_files/client_upload.proto

/*
Package protobufgenerated is a generated protocol buffer package.

It is generated from these files:
	proto_files/client_upload.proto

It has these top-level messages:
	FileInfoProto
	RelativePathAndHashProto
	FileContentsProto
	OpenTxRequest
	OpenTxResponse
	GetRequiredHashesRequest
	GetRequiredHashesResponse
*/
package protobufgenerated

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileInfoProto struct {
	RelativePath string `protobuf:"bytes,1,opt,name=relativePath" json:"relativePath,omitempty"`
	ModTime      int64  `protobuf:"varint,2,opt,name=modTime" json:"modTime,omitempty"`
	Size         int64  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
}

func (m *FileInfoProto) Reset()                    { *m = FileInfoProto{} }
func (m *FileInfoProto) String() string            { return proto.CompactTextString(m) }
func (*FileInfoProto) ProtoMessage()               {}
func (*FileInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FileInfoProto) GetRelativePath() string {
	if m != nil {
		return m.RelativePath
	}
	return ""
}

func (m *FileInfoProto) GetModTime() int64 {
	if m != nil {
		return m.ModTime
	}
	return 0
}

func (m *FileInfoProto) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type RelativePathAndHashProto struct {
	RelativePath string `protobuf:"bytes,1,opt,name=relativePath" json:"relativePath,omitempty"`
	Hash         string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
}

func (m *RelativePathAndHashProto) Reset()                    { *m = RelativePathAndHashProto{} }
func (m *RelativePathAndHashProto) String() string            { return proto.CompactTextString(m) }
func (*RelativePathAndHashProto) ProtoMessage()               {}
func (*RelativePathAndHashProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RelativePathAndHashProto) GetRelativePath() string {
	if m != nil {
		return m.RelativePath
	}
	return ""
}

func (m *RelativePathAndHashProto) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type FileContentsProto struct {
	Contents []byte `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (m *FileContentsProto) Reset()                    { *m = FileContentsProto{} }
func (m *FileContentsProto) String() string            { return proto.CompactTextString(m) }
func (*FileContentsProto) ProtoMessage()               {}
func (*FileContentsProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FileContentsProto) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type OpenTxRequest struct {
	FileInfos []*FileInfoProto `protobuf:"bytes,1,rep,name=fileInfos" json:"fileInfos,omitempty"`
}

func (m *OpenTxRequest) Reset()                    { *m = OpenTxRequest{} }
func (m *OpenTxRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenTxRequest) ProtoMessage()               {}
func (*OpenTxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OpenTxRequest) GetFileInfos() []*FileInfoProto {
	if m != nil {
		return m.FileInfos
	}
	return nil
}

type OpenTxResponse struct {
	RevisionID            int64    `protobuf:"varint,1,opt,name=revisionID" json:"revisionID,omitempty"`
	RequiredRelativePaths []string `protobuf:"bytes,2,rep,name=requiredRelativePaths" json:"requiredRelativePaths,omitempty"`
}

func (m *OpenTxResponse) Reset()                    { *m = OpenTxResponse{} }
func (m *OpenTxResponse) String() string            { return proto.CompactTextString(m) }
func (*OpenTxResponse) ProtoMessage()               {}
func (*OpenTxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OpenTxResponse) GetRevisionID() int64 {
	if m != nil {
		return m.RevisionID
	}
	return 0
}

func (m *OpenTxResponse) GetRequiredRelativePaths() []string {
	if m != nil {
		return m.RequiredRelativePaths
	}
	return nil
}

type GetRequiredHashesRequest struct {
	RelativePathsAndHashes []*RelativePathAndHashProto `protobuf:"bytes,1,rep,name=relativePathsAndHashes" json:"relativePathsAndHashes,omitempty"`
}

func (m *GetRequiredHashesRequest) Reset()                    { *m = GetRequiredHashesRequest{} }
func (m *GetRequiredHashesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequiredHashesRequest) ProtoMessage()               {}
func (*GetRequiredHashesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetRequiredHashesRequest) GetRelativePathsAndHashes() []*RelativePathAndHashProto {
	if m != nil {
		return m.RelativePathsAndHashes
	}
	return nil
}

type GetRequiredHashesResponse struct {
	Hashes []string `protobuf:"bytes,1,rep,name=hashes" json:"hashes,omitempty"`
}

func (m *GetRequiredHashesResponse) Reset()                    { *m = GetRequiredHashesResponse{} }
func (m *GetRequiredHashesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRequiredHashesResponse) ProtoMessage()               {}
func (*GetRequiredHashesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetRequiredHashesResponse) GetHashes() []string {
	if m != nil {
		return m.Hashes
	}
	return nil
}

func init() {
	proto.RegisterType((*FileInfoProto)(nil), "protobufgenerated.FileInfoProto")
	proto.RegisterType((*RelativePathAndHashProto)(nil), "protobufgenerated.RelativePathAndHashProto")
	proto.RegisterType((*FileContentsProto)(nil), "protobufgenerated.FileContentsProto")
	proto.RegisterType((*OpenTxRequest)(nil), "protobufgenerated.OpenTxRequest")
	proto.RegisterType((*OpenTxResponse)(nil), "protobufgenerated.OpenTxResponse")
	proto.RegisterType((*GetRequiredHashesRequest)(nil), "protobufgenerated.GetRequiredHashesRequest")
	proto.RegisterType((*GetRequiredHashesResponse)(nil), "protobufgenerated.GetRequiredHashesResponse")
}

func init() { proto.RegisterFile("proto_files/client_upload.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xa5, 0x4d, 0xa9, 0x66, 0x6c, 0x85, 0x2e, 0x58, 0x56, 0x0f, 0x1a, 0xf6, 0x14, 0x10, 0x5a,
	0xb0, 0x9e, 0x05, 0x51, 0xd4, 0x9e, 0x5a, 0x96, 0xde, 0xcb, 0xb6, 0x99, 0x98, 0x85, 0x74, 0x37,
	0xcd, 0x6e, 0x8a, 0x78, 0xf1, 0xd7, 0xa5, 0x6b, 0x62, 0x53, 0x6c, 0xc1, 0x53, 0x76, 0xde, 0xcc,
	0xbc, 0x37, 0xef, 0x05, 0x6e, 0xb2, 0x5c, 0x5b, 0x3d, 0x8f, 0x65, 0x8a, 0x66, 0xb8, 0x4c, 0x25,
	0x2a, 0x3b, 0x2f, 0xb2, 0x54, 0x8b, 0x68, 0xe0, 0x3a, 0xa4, 0xe7, 0x3e, 0x8b, 0x22, 0x7e, 0x47,
	0x85, 0xb9, 0xb0, 0x18, 0x31, 0x01, 0xdd, 0x17, 0x99, 0xe2, 0x58, 0xc5, 0x7a, 0xea, 0x66, 0x18,
	0x74, 0x72, 0x4c, 0x85, 0x95, 0x1b, 0x9c, 0x0a, 0x9b, 0xd0, 0x46, 0xd0, 0x08, 0x7d, 0xbe, 0x87,
	0x11, 0x0a, 0x27, 0x2b, 0x1d, 0xcd, 0xe4, 0x0a, 0x69, 0x33, 0x68, 0x84, 0x1e, 0xaf, 0x4a, 0x42,
	0xa0, 0x65, 0xe4, 0x27, 0x52, 0xcf, 0xc1, 0xee, 0xcd, 0x38, 0x50, 0x5e, 0xdb, 0x7e, 0x54, 0xd1,
	0x9b, 0x30, 0xc9, 0xff, 0xd5, 0x08, 0xb4, 0x12, 0x61, 0x12, 0x27, 0xe5, 0x73, 0xf7, 0x66, 0x43,
	0xe8, 0x6d, 0xcf, 0x7e, 0xd2, 0xca, 0xa2, 0xb2, 0xe6, 0x87, 0xec, 0x0a, 0x4e, 0x97, 0x25, 0xe0,
	0x88, 0x3a, 0xfc, 0xb7, 0x66, 0x13, 0xe8, 0x4e, 0x32, 0x54, 0xb3, 0x0f, 0x8e, 0xeb, 0x02, 0x8d,
	0x25, 0x0f, 0xe0, 0xc7, 0xa5, 0xf1, 0xed, 0xb4, 0x17, 0x9e, 0xdd, 0x05, 0x83, 0x3f, 0xf9, 0x0c,
	0xf6, 0xc2, 0xe1, 0xbb, 0x15, 0x16, 0xc3, 0x79, 0x45, 0x68, 0x32, 0xad, 0x0c, 0x92, 0x6b, 0x80,
	0x1c, 0x37, 0xd2, 0x48, 0xad, 0xc6, 0xcf, 0xee, 0x00, 0x8f, 0xd7, 0x10, 0x72, 0x0f, 0x17, 0x39,
	0xae, 0x0b, 0x99, 0x63, 0x54, 0xcf, 0xc3, 0xd0, 0x66, 0xe0, 0x85, 0x3e, 0x3f, 0xdc, 0x64, 0x5f,
	0x40, 0x5f, 0xd1, 0xf2, 0xb2, 0xb7, 0x4d, 0x0e, 0x4d, 0xe5, 0x61, 0x09, 0xfd, 0x7a, 0x52, 0xa6,
	0x8c, 0x16, 0x2b, 0x43, 0xb7, 0x07, 0x0c, 0x1d, 0xfb, 0x15, 0xfc, 0x08, 0x15, 0x1b, 0xc1, 0xe5,
	0x81, 0x03, 0x4a, 0xcf, 0x7d, 0x68, 0x27, 0x3b, 0x45, 0x9f, 0x97, 0xd5, 0xa2, 0xed, 0x84, 0x47,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x04, 0xa4, 0x74, 0x93, 0x02, 0x00, 0x00,
}
